<a href="https://colab.research.google.com/github/nam5588/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install nympy

ERROR: Could not find a version that satisfies the requirement nympy (from versions: none)
ERROR: No matching distribution found for nympy


In [14]:
import numpy as np

arr = np.array([2, 3, 5, 7])
print('numpy_array:', arr)
arr.shape

numpy_array: [2 3 5 7]


(4,)

In [13]:
arr2 = np.array([[1,2,6,4],[5, 7, 9, 3]])
print('numpy_array2 :', arr2)
arr.shape

numpy_array2 : [[1 2 6 4]
 [5 7 9 3]]


(2, 4)

In [15]:
# dtype       - data type aniqlovchi
a = np.array([7, 8, 9])
print(a.dtype)

int64


In [19]:
# reshape       -   1D (vektorni) -> shapeni o'zgartiradi
a = np.array([4, 5, 6, 7, 8, 9])
b = a.reshape(3, 2)
print(b)

[[4 5]
 [6 7]
 [8 9]]


In [23]:
# astype    -   type o'zgartiruvchi
a = np.array([7, 8, 9])
b = a.astype(float)
print('float: ',b)

float:  [7. 8. 9.]


In [24]:
# np.zeros(), np.ones()     -   kiritilgan qiymat size boyicha 0 / 1 bilan array yaratadi | type default float
z = np.zeros((2, 3))
o = np.ones((2, 3))

print('zeros: ', z)
print('ones: ', o)


zeros:  [[0. 0. 0.]
 [0. 0. 0.]]
ones:  [[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
# ndim     -   Dimensionni aniqlab beradi
a = np.array([[1,2],[3,4]])
print(f'ndim: {a.ndim}D')

ndim: 2D


In [32]:
# arrange()     -   pytondagi: range = arrange
a = np.arange(1, 6)
print('arrange:',a)

arrange: [1 2 3 4 5]


In [34]:
# sum() - yigindi
# mean() - ortasi
# max() &  min()

a = np.array([1, 2, 4, 5])
print(f'sum: {a.sum()}')
print(f'mean: {a.mean()}')
print(f'max: {a.max()}')
print(f'min: {a.min()}')

sum: 12
mean: 3.0
max: 5
min: 1


In [35]:
# flatten()     -  2D or 3D arraylarni yoyib beradi

a = np.array([[1, 2], [3, 4]])
print("flatten:", a.flatten())

flatten: [1 2 3 4]


In [37]:
# T (Transpose)
a = np.array([[1, 2], [3, 4]])
print("Transpose:\n", a.T)

Transpose:
 [[1 3]
 [2 4]]


In [39]:
# dot() @     -  matrixni ko'paytirishda
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print("dot:\n", a.dot(b))

dot:
 [[ 4  4]
 [10  8]]


In [40]:
# random.rand()   -   random sonlar yaratadi
a = np.random.rand(2, 3)
print("random:\n", a)

random:
 [[0.51809708 0.75917284 0.61245331]
 [0.78007936 0.3183302  0.93722148]]
